# Generated by Django 2.2.1 on 2019-05-17 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('isPublished', models.BooleanField(default=False)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('cover_image_url', models.URLField(max_length=300)),
                ('max_marks_per_quiz', models.IntegerField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('syllabus', models.TextField()),
                ('full_marks', models.IntegerField()),
                ('allotted_time_in_minutes', models.IntegerField()),
                ('negative_marking', models.BooleanField(default=False)),
                ('cover_image_url', models.URLField(max_length=300)),
                ('isActive', models.BooleanField(default=False)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('quizset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuizSet')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('pub_time', models.TimeField(auto_now_add=True)),
                ('marks', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.TextField()),
                ('isCorrect', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Question')),
            ],
        ),
    ]
